
const googleFonts = [
    { name: "Roboto", value: "Roboto" },
    { name: "Open Sans", value: "Open Sans" },
    { name: "Lato", value: "Lato" },
    { name: "Montserrat", value: "Montserrat" },
    { name: "Oswald", value: "Oswald" },
    { name: "Source Sans Pro", value: "Source Sans Pro" },
    { name: "Raleway", value: "Raleway" },
    { name: "PT Sans", value: "PT Sans" },
    { name: "Noto Sans", value: "Noto Sans" },
    { name: "Roboto Condensed", value: "Roboto Condensed" },
    { name: "Poppins", value: "Poppins" },
    { name: "Ubuntu", value: "Ubuntu" },
    { name: "Roboto Slab", value: "Roboto Slab" },
    { name: "Merriweather", value: "Merriweather" },
    { name: "Fira Sans", value: "Fira Sans" },
    { name: "Roboto Mono", value: "Roboto Mono" },
    { name: "Playfair Display", value: "Playfair Display" },
    { name: "Muli", value: "Muli" },
    { name: "Nunito", value: "Nunito" },
    { name: "PT Serif", value: "PT Serif" },
    { name: "Titillium Web", value: "Titillium Web" },
    { name: "Noto Serif", value: "Noto Serif" },
    { name: "Quicksand", value: "Quicksand" },
    { name: "Work Sans", value: "Work Sans" },
    { name: "Nanum Gothic", value: "Nanum Gothic" },
    { name: "Cabin", value: "Cabin" },
    { name: "Lora", value: "Lora" },
    { name: "Exo", value: "Exo" },
    { name: "Zilla Slab", value: "Zilla Slab" },
    { name: "Arimo", value: "Arimo" },
    { name: "Oxygen", value: "Oxygen" },
    { name: "Karla", value: "Karla" },
    { name: "Cormorant Garamond", value: "Cormorant Garamond" },
    { name: "Libre Franklin", value: "Libre Franklin" },
    { name: "Inconsolata", value: "Inconsolata" },
    { name: "Barlow", value: "Barlow" },
    { name: "Hind", value: "Hind" },
    { name: "Rubik", value: "Rubik" },
    { name: "Archivo", value: "Archivo" },
    { name: "Merriweather Sans", value: "Merriweather Sans" },
    { name: "Libre Baskerville", value: "Libre Baskerville" },
    { name: "Heebo", value: "Heebo" },
    { name: "Space Mono", value: "Space Mono" },
    { name: "Bitter", value: "Bitter" },
    { name: "Arvo", value: "Arvo" },
    { name: "Josefin Sans", value: "Josefin Sans" },
    { name: "IBM Plex Sans", value: "IBM Plex Sans" },
    { name: "Old Standard TT", value: "Old Standard TT" },
    { name: "Vollkorn", value: "Vollkorn" },
    { name: "Abel", value: "Abel" },
    { name: "Fjalla One", value: "Fjalla One" },
    { name: "Cairo", value: "Cairo" },
    { name: "Asap", value: "Asap" },
    { name: "Cinzel", value: "Cinzel" },
    { name: "Anton", value: "Anton" },
    { name: "PT Sans Narrow", value: "PT Sans Narrow" },
    { name: "Istok Web", value: "Istok Web" },
    { name: "Amatic SC", value: "Amatic SC" },
    { name: "Orbitron", value: "Orbitron" },
    { name: "Assistant", value: "Assistant" },
    { name: "Signika", value: "Signika" },
    { name: "Lobster", value: "Lobster" },
    { name: "Julius Sans One", value: "Julius Sans One" },
    { name: "Pathway Gothic One", value: "Pathway Gothic One" },
    { name: "Russo One", value: "Russo One" },
    { name: "Fredoka One", value: "Fredoka One" },
    { name: "Yanone Kaffeesatz", value: "Yanone Kaffeesatz" },
    { name: "Bree Serif", value: "Bree Serif" },
    { name: "Nobile", value: "Nobile" },
    { name: "Satisfy", value: "Satisfy" },
    { name: "Cuprum", value: "Cuprum" },
    { name: "Chivo", value: "Chivo" },
    { name: "Permanent Marker", value: "Permanent Marker" },
    { name: "Kreon", value: "Kreon" },
    { name: "Maven Pro", value: "Maven Pro" }
];

export default googleFonts;